# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 602)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sh/Secret-Hitler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/*background-color: rgb(0, 0, 0);*/\n"
"background-color: rgb(230, 99, 66);\n"
"color: rgb(248, 227, 192);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_min = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/controls/min.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon1)
        self.pushButton_min.setFlat(True)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_4.addWidget(self.pushButton_min)
        self.pushButton_max = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/controls/max.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_max.setIcon(icon2)
        self.pushButton_max.setFlat(True)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_4.addWidget(self.pushButton_max)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/controls/close.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon3)
        self.pushButton_close.setCheckable(False)
        self.pushButton_close.setAutoDefault(False)
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_4.addWidget(self.pushButton_close)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 227, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 99, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.toolBox.setPalette(palette)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet("color: rgb(248, 227, 192);\n"
"background-color: rgb(230, 99, 66);\n"
"selected-color: rgb(248, 227, 192);\n"
"selection-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QtWidgets.QWidget()
        self.toolBoxPage1.setStyleSheet("")
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.toolBoxPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.toolBoxPage1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_president = QtWidgets.QComboBox(self.toolBoxPage1)
        self.comboBox_president.setStyleSheet("color: rgb(248, 227, 192);\n"
"background-color: rgb(230, 99, 66);\n"
"selection-color: rgb(230, 99, 66);\n"
"selection-background-color: rgb(248, 227, 192);")
        self.comboBox_president.setObjectName("comboBox_president")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_president)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.toolBoxPage1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_chancellor = QtWidgets.QComboBox(self.toolBoxPage1)
        self.comboBox_chancellor.setStyleSheet("color: rgb(248, 227, 192);\n"
"background-color: rgb(230, 99, 66);\n"
"selection-color: rgb(230, 99, 66);\n"
"selection-background-color: rgb(248, 227, 192);")
        self.comboBox_chancellor.setObjectName("comboBox_chancellor")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_chancellor)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_pass = QtWidgets.QPushButton(self.toolBoxPage1)
        self.pushButton_pass.setObjectName("pushButton_pass")
        self.verticalLayout.addWidget(self.pushButton_pass)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.toolBoxPage2 = QtWidgets.QWidget()
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.toolBoxPage2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_pres_info_1 = QtWidgets.QLabel(self.toolBoxPage2)
        self.label_pres_info_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pres_info_1.setObjectName("label_pres_info_1")
        self.gridLayout_3.addWidget(self.label_pres_info_1, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.toolBoxPage2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_about_player = QtWidgets.QComboBox(self.toolBoxPage2)
        self.comboBox_about_player.setStyleSheet("color: rgb(248, 227, 192);\n"
"background-color: rgb(230, 99, 66);\n"
"selection-color: rgb(230, 99, 66);\n"
"selection-background-color: rgb(248, 227, 192);")
        self.comboBox_about_player.setObjectName("comboBox_about_player")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_about_player)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.pushButton_reveal = QtWidgets.QPushButton(self.toolBoxPage2)
        self.pushButton_reveal.setObjectName("pushButton_reveal")
        self.gridLayout_3.addWidget(self.pushButton_reveal, 2, 0, 1, 1)
        self.toolBox.addItem(self.toolBoxPage2, "")
        self.toolBoxPage3 = QtWidgets.QWidget()
        self.toolBoxPage3.setObjectName("toolBoxPage3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.toolBoxPage3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_pres_info_2 = QtWidgets.QLabel(self.toolBoxPage3)
        self.label_pres_info_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pres_info_2.setObjectName("label_pres_info_2")
        self.verticalLayout_3.addWidget(self.label_pres_info_2)
        self.pushButton_examine = QtWidgets.QPushButton(self.toolBoxPage3)
        self.pushButton_examine.setObjectName("pushButton_examine")
        self.verticalLayout_3.addWidget(self.pushButton_examine)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.toolBoxPage3, "")
        self.toolBoxPage4 = QtWidgets.QWidget()
        self.toolBoxPage4.setObjectName("toolBoxPage4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.toolBoxPage4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_enact = QtWidgets.QPushButton(self.toolBoxPage4)
        self.pushButton_enact.setObjectName("pushButton_enact")
        self.gridLayout_4.addWidget(self.pushButton_enact, 0, 0, 1, 1)
        self.toolBox.addItem(self.toolBoxPage4, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setStyleSheet("color: rgb(230, 99, 66);\n"
"background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(230, 99, 66)")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background: rgb(0,0,0); color: rgb(230, 99, 60)")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_New_Game = QtWidgets.QAction(MainWindow)
        self.actionStart_New_Game.setObjectName("actionStart_New_Game")
        self.actionUpdate_Players = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Players.setObjectName("actionUpdate_Players")
        self.actionPlayer_Settings = QtWidgets.QAction(MainWindow)
        self.actionPlayer_Settings.setCheckable(False)
        self.actionPlayer_Settings.setObjectName("actionPlayer_Settings")
        self.actionAdd_Sender_Email = QtWidgets.QAction(MainWindow)
        self.actionAdd_Sender_Email.setObjectName("actionAdd_Sender_Email")
        self.menuFile.addAction(self.actionStart_New_Game)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPlayer_Settings)
        self.menuFile.addAction(self.actionAdd_Sender_Email)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Secret Hitler"))
        self.label_3.setText(_translate("MainWindow", "Welcome to Secret Hitler!"))
        self.label.setText(_translate("MainWindow", "President"))
        self.comboBox_president.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_president.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_president.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_president.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_president.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_president.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_president.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_president.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_president.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_president.setItemText(9, _translate("MainWindow", "Benj"))
        self.label_2.setText(_translate("MainWindow", "Chancellor"))
        self.comboBox_chancellor.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_chancellor.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_chancellor.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_chancellor.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_chancellor.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_chancellor.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_chancellor.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_chancellor.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_chancellor.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_chancellor.setItemText(9, _translate("MainWindow", "Benj"))
        self.pushButton_pass.setText(_translate("MainWindow", "Pass Policies"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("MainWindow", "Pass Policies"))
        self.label_pres_info_1.setText(_translate("MainWindow", "Info about president..."))
        self.label_4.setText(_translate("MainWindow", "Player to be revealed to president:"))
        self.comboBox_about_player.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_about_player.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_about_player.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_about_player.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_about_player.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_about_player.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_about_player.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_about_player.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_about_player.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_about_player.setItemText(9, _translate("MainWindow", "Benj"))
        self.pushButton_reveal.setText(_translate("MainWindow", "Reveal Party"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), _translate("MainWindow", "Reveal Party"))
        self.label_pres_info_2.setText(_translate("MainWindow", "Info about president..."))
        self.pushButton_examine.setText(_translate("MainWindow", "Examine Top Three"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage3), _translate("MainWindow", "Examine Top Three"))
        self.pushButton_enact.setText(_translate("MainWindow", "Enact Top Policy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage4), _translate("MainWindow", "Enact Top Policy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionStart_New_Game.setText(_translate("MainWindow", "Start New Game"))
        self.actionStart_New_Game.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionUpdate_Players.setText(_translate("MainWindow", "Update Players"))
        self.actionUpdate_Players.setShortcut(_translate("MainWindow", "Shift+U"))
        self.actionPlayer_Settings.setText(_translate("MainWindow", "Update Players"))
        self.actionPlayer_Settings.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionAdd_Sender_Email.setText(_translate("MainWindow", "Add Sender Email"))
        self.actionAdd_Sender_Email.setShortcut(_translate("MainWindow", "Ctrl+E"))
import sh_rc
