# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 288)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_president = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_president.setObjectName("comboBox_president")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_president)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_chancellor = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_chancellor.setObjectName("comboBox_chancellor")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_chancellor)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_pass = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pass.setObjectName("pushButton_pass")
        self.verticalLayout.addWidget(self.pushButton_pass)
        self.pushButton_reveal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reveal.setObjectName("pushButton_reveal")
        self.verticalLayout.addWidget(self.pushButton_reveal)
        self.pushButton_examine = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_examine.setObjectName("pushButton_examine")
        self.verticalLayout.addWidget(self.pushButton_examine)
        self.pushButton_enact = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enact.setObjectName("pushButton_enact")
        self.verticalLayout.addWidget(self.pushButton_enact)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlayers = QtWidgets.QMenu(self.menubar)
        self.menuPlayers.setObjectName("menuPlayers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_New_Game = QtWidgets.QAction(MainWindow)
        self.actionStart_New_Game.setObjectName("actionStart_New_Game")
        self.actionUpdate_Players = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Players.setObjectName("actionUpdate_Players")
        self.actionUpdate_Players_2 = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Players_2.setObjectName("actionUpdate_Players_2")
        self.menuFile.addAction(self.actionStart_New_Game)
        self.menuFile.addSeparator()
        self.menuPlayers.addAction(self.actionUpdate_Players_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlayers.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "President"))
        self.comboBox_president.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_president.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_president.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_president.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_president.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_president.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_president.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_president.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_president.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_president.setItemText(9, _translate("MainWindow", "Benj"))
        self.label_2.setText(_translate("MainWindow", "Chancellor"))
        self.comboBox_chancellor.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_chancellor.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_chancellor.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_chancellor.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_chancellor.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_chancellor.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_chancellor.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_chancellor.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_chancellor.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_chancellor.setItemText(9, _translate("MainWindow", "Benj"))
        self.pushButton_pass.setText(_translate("MainWindow", "Pass Sequence"))
        self.pushButton_reveal.setText(_translate("MainWindow", "Reveal Party"))
        self.pushButton_examine.setText(_translate("MainWindow", "Examine Top Three"))
        self.pushButton_enact.setText(_translate("MainWindow", "Enact Top Policy"))
        self.label_3.setText(_translate("MainWindow", "Welcome to Secret Hitler!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPlayers.setTitle(_translate("MainWindow", "Players"))
        self.actionStart_New_Game.setText(_translate("MainWindow", "Start New Game"))
        self.actionUpdate_Players.setText(_translate("MainWindow", "Update Players"))
        self.actionUpdate_Players_2.setText(_translate("MainWindow", "Update Players"))
