# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_president = QtWidgets.QComboBox(self.tab)
        self.comboBox_president.setObjectName("comboBox_president")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.comboBox_president.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_president)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_chancellor = QtWidgets.QComboBox(self.tab)
        self.comboBox_chancellor.setObjectName("comboBox_chancellor")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.comboBox_chancellor.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_chancellor)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_pass = QtWidgets.QPushButton(self.tab)
        self.pushButton_pass.setObjectName("pushButton_pass")
        self.verticalLayout.addWidget(self.pushButton_pass)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_pres_info_1 = QtWidgets.QLabel(self.tab_2)
        self.label_pres_info_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pres_info_1.setObjectName("label_pres_info_1")
        self.gridLayout_3.addWidget(self.label_pres_info_1, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_about_player = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_about_player.setObjectName("comboBox_about_player")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.comboBox_about_player.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_about_player)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.pushButton_reveal = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_reveal.setObjectName("pushButton_reveal")
        self.gridLayout_3.addWidget(self.pushButton_reveal, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_pres_info_2 = QtWidgets.QLabel(self.tab_3)
        self.label_pres_info_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pres_info_2.setObjectName("label_pres_info_2")
        self.verticalLayout_3.addWidget(self.label_pres_info_2)
        self.pushButton_examine = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_examine.setObjectName("pushButton_examine")
        self.verticalLayout_3.addWidget(self.pushButton_examine)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_enact = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_enact.setObjectName("pushButton_enact")
        self.gridLayout_4.addWidget(self.pushButton_enact, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlayers = QtWidgets.QMenu(self.menubar)
        self.menuPlayers.setObjectName("menuPlayers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_New_Game = QtWidgets.QAction(MainWindow)
        self.actionStart_New_Game.setObjectName("actionStart_New_Game")
        self.actionUpdate_Players = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Players.setObjectName("actionUpdate_Players")
        self.actionUpdate_Players_2 = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Players_2.setObjectName("actionUpdate_Players_2")
        self.menuFile.addAction(self.actionStart_New_Game)
        self.menuFile.addSeparator()
        self.menuPlayers.addAction(self.actionUpdate_Players_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlayers.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Welcome to Secret Hitler!"))
        self.label.setText(_translate("MainWindow", "President"))
        self.comboBox_president.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_president.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_president.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_president.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_president.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_president.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_president.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_president.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_president.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_president.setItemText(9, _translate("MainWindow", "Benj"))
        self.label_2.setText(_translate("MainWindow", "Chancellor"))
        self.comboBox_chancellor.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_chancellor.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_chancellor.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_chancellor.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_chancellor.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_chancellor.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_chancellor.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_chancellor.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_chancellor.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_chancellor.setItemText(9, _translate("MainWindow", "Benj"))
        self.pushButton_pass.setText(_translate("MainWindow", "Pass Policies"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Pass Policies"))
        self.label_pres_info_1.setText(_translate("MainWindow", "Info about president..."))
        self.label_4.setText(_translate("MainWindow", "Player to be revealed to president:"))
        self.comboBox_about_player.setItemText(0, _translate("MainWindow", "Bryan"))
        self.comboBox_about_player.setItemText(1, _translate("MainWindow", "Kristen"))
        self.comboBox_about_player.setItemText(2, _translate("MainWindow", "Jason"))
        self.comboBox_about_player.setItemText(3, _translate("MainWindow", "Bryant"))
        self.comboBox_about_player.setItemText(4, _translate("MainWindow", "Josh"))
        self.comboBox_about_player.setItemText(5, _translate("MainWindow", "Monica"))
        self.comboBox_about_player.setItemText(6, _translate("MainWindow", "Jackson"))
        self.comboBox_about_player.setItemText(7, _translate("MainWindow", "Aleska"))
        self.comboBox_about_player.setItemText(8, _translate("MainWindow", "Judith"))
        self.comboBox_about_player.setItemText(9, _translate("MainWindow", "Benj"))
        self.pushButton_reveal.setText(_translate("MainWindow", "Reveal Party"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Reveal Party"))
        self.label_pres_info_2.setText(_translate("MainWindow", "Info about president..."))
        self.pushButton_examine.setText(_translate("MainWindow", "Examine Top Three"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Examine Top Cards"))
        self.pushButton_enact.setText(_translate("MainWindow", "Enact Top Policy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Enact Top Policy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPlayers.setTitle(_translate("MainWindow", "Players"))
        self.actionStart_New_Game.setText(_translate("MainWindow", "Start New Game"))
        self.actionUpdate_Players.setText(_translate("MainWindow", "Update Players"))
        self.actionUpdate_Players_2.setText(_translate("MainWindow", "Update Players"))
